name: Deploy prebuilt ASP.NET Core app to Azure Web App - augustusdynamics

on:
  push:
    branches:
      - azure-deployment-package  # branch with prebuilt files
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout deploy branch
        uses: actions/checkout@v4

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'augustusdynamics'
          slot-name: 'Production'
          package: .                     # assumes prebuilt files are in root
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_03E1EC878AEE41A78465D6E7E1DA9601 }}
